# Site settings
title: Wincci Zhou
description: Personal Profile
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Wincci Developer
user_description: I graduated from University of Waterloo Engineering, with an interest in Machine Learning and UI development. My dream career is jobs that combines technology and art, which are both what I am passionate about.
user_title: Software Developer
email: yingsi.zhou@uwaterloo.ca
twitter_username: greenconcertina
github_username:  winccichow
instagram_username:  wincci.ys.zhou

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
