# Site settings
name: Wincci Zhou
title: Wincci Zhou | Front End Software Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://winccichow.github.io/
baseurl: ''
email: y438zhou@uwaterloo.ca
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:y438zhou@uwaterloo.ca
  - title: twitter
    url: https://twitter.com/greenconcertina
  - title: instagram
    url: https://instagram.com/wincci.ys.zhou
  - title: codepen
    url: http://codepen.io/winccichow
  - title: github
    url: https://github.com/winccichow
  - title: linkedin
    url: https://www.linkedin.com//in/winccizhou

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
