# User config
author: "Wincci Zhou"
tagline: "Wincci the Developer"
description: "I am a proud UWaterloo Engineering graduate, with an interest in UI development. Because it combines my passion for technology and art."
keywords: "UI Designer, Front End Developer, Software Engineer"
email: "yingsi.zhou@uwaterloo.ca"
linkedin: "https://www.linkedin.com/in/winccizhou"
twitter: "https://twitter.com/greenconcertina"
github: "https://github.com/winccichow"

# Site config
baseurl: "https://winccichow.github.io"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
