# User config
author: "Wincci Z"
tagline: "Wincci the Developer"
description: "I an Engineering graduate from University of Waterloo, with an interest in cognitive ergonomics and UI development. My dream career is jobs that combines technology and art, which are both what I am passionate about."
keywords: "UI Designer, Front End Developer, Software Engineer"
email: "yingsi.zhou@uwaterloo.ca"
linkedin: "https://www.linkedin.com/in/winccizhou"
twitter: "https://twitter.com/greenconcertina"
github: "https://github.com/winccichow"

# Site config
baseurl: "https://winccichow.github.io"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
