# User config
author: "Wincci Z"
tagline: "Wincci the Developer"
description: "I graduated from University of Waterloo Engineering, with an interest in Machine Learning and UI development. My dream career is jobs that combines technology and art, which are both what I am passionate about."
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "yingsi.zhou@uwaterloo.ca"
linkedin: "https://www.linkedin.com/in/winccizhou"
twitter: "https://twitter.com/greenconcertina"
github: "https://github.com/winccichow"

# Site config
baseurl: "https://winccichow.github.io/"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
